import { defineConfig } from 'astro/config';
import { copyFile, readdir, writeFile } from 'node:fs/promises';

/**
 * `_headers`, written at build time rather than kept as a static file.
 *
 * The CSP has to name the analytics origin, and that origin is configuration
 * (UMAMI_SCRIPT_URL) rather than a constant. A hand-maintained CSP would go
 * stale the first time the client moves their Umami instance, and a CSP that
 * silently blocks the analytics script is close to invisible — no visual
 * symptom, just a console entry nobody reads and a dashboard that stays empty.
 * Generating it means the policy and the script can never disagree.
 *
 * Deliberate choices:
 *  - `script-src 'self' 'unsafe-inline'`: the theme switch has to run before
 *    first paint to avoid a flash, so it is an inline script by design
 *    (SKILL.md §1). Hashes were considered — Astro rewrites the inline theme
 *    script per page, so the hash set would have to be collected per route
 *    and the nonce path needs a server. 'unsafe-inline' is the honest choice
 *    here; there is no user-generated content anywhere on the site.
 *  - `frame-src` for Turnstile: the widget renders in an iframe.
 *  - `connect-src` for Umami: it POSTs its events back to its own host.
 *  - no `upgrade-insecure-requests`: everything is already https.
 */
const securityHeaders = () => {
  const umami = process.env.UMAMI_SCRIPT_URL ?? '';
  let umamiOrigin = '';
  if (umami) {
    try {
      umamiOrigin = new URL(umami).origin;
    } catch {
      throw new Error(`UMAMI_SCRIPT_URL is not a valid URL: ${umami}`);
    }
  }

  const turnstile = 'https://challenges.cloudflare.com';
  const csp = [
    `default-src 'self'`,
    `base-uri 'self'`,
    `form-action 'self'`,
    `frame-ancestors 'none'`,
    `object-src 'none'`,
    `img-src 'self' data:`,
    `font-src 'self'`,
    `style-src 'self' 'unsafe-inline'`,
    `script-src 'self' 'unsafe-inline' ${turnstile}${umamiOrigin ? ` ${umamiOrigin}` : ''}`,
    `frame-src ${turnstile}`,
    // Turnstile is in connect-src as well as frame-src and script-src: the
    // widget XHRs back to its own host to fetch and redeem the challenge, and
    // with only frame-src it fails with an opaque error rather than a CSP
    // message anyone would connect to this file.
    `connect-src 'self' ${turnstile}${umamiOrigin ? ` ${umamiOrigin}` : ''}`,
  ].join('; ');

  return {
    name: 'security-headers',
    hooks: {
      'astro:build:done': async ({ dir, logger }) => {
        const body = `# Generated by astro.config.mjs — do not edit dist/_headers by hand.
# The CSP names the analytics origin, which comes from UMAMI_SCRIPT_URL.

# ONE \`/*\` SECTION, NOT TWO.
#
# This file used to declare \`/*\` twice: security headers at the top, then a
# Cache-Control-only \`/*\` at the bottom. Cloudflare Pages keeps the LAST
# section for a repeated path and drops the earlier one, so production served
# the Cache-Control and none of the security headers — verified against the
# live site on 2026-08-14, which returned no Content-Security-Policy,
# Strict-Transport-Security, Permissions-Policy, Cross-Origin-Opener-Policy or
# X-Frame-Options, while \`/fonts/*\` and \`/og/*\` (declared once each) applied
# correctly. Keep every \`/*\` rule in this one section.
#
# Cache-Control here is the HTML rule: HTML must revalidate, because the
# studio's age and the year are baked in at build time and the weekly rebuild
# is what keeps them true. The path sections below override it.
/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), autoplay=(), camera=(), display-capture=(), encrypted-media=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=(), xr-spatial-tracking=()
  Cross-Origin-Opener-Policy: same-origin
  X-Frame-Options: DENY
  Cache-Control: public, max-age=0, must-revalidate

# Fingerprinted by Astro — safe to cache for a year.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

# Self-hosted and never renamed in place; a year is still right because a new
# family would ship under a new filename.
/fonts/*
  Cache-Control: public, max-age=31536000, immutable

# Rendered at build, content-addressed by route, cheap to revalidate.
/og/*
  Cache-Control: public, max-age=86400, stale-while-revalidate=604800
`;
        await writeFile(new URL('_headers', dir), body, 'utf8');
        logger.info(
          umamiOrigin
            ? `wrote _headers, CSP allows ${umamiOrigin}`
            : 'wrote _headers, no analytics origin set'
        );
      },
    },
  };
};

/**
 * Cloudflare Pages picks an error page by walking up from the requested path
 * looking for `404.html`. Astro only special-cases the root `404.astro`; the
 * localised ones build to `ru/404/index.html`, which that walk never finds, so
 * a miss under /ru/ would be answered in Azerbaijani.
 *
 * This copies each localised 404 to the sibling `404.html` the walk expects.
 * The directory version stays where it is — it is a real, linkable page and
 * the language switcher moves between them.
 */
const localisedErrorPages = () => ({
  name: 'localised-404',
  hooks: {
    'astro:build:done': async ({ dir, logger }) => {
      for (const locale of ['ru', 'en']) {
        const from = new URL(`${locale}/404/index.html`, dir);
        const to = new URL(`${locale}/404.html`, dir);
        await copyFile(from, to);
        logger.info(`wrote ${locale}/404.html for the Cloudflare error-page lookup`);
      }
      const names = await readdir(dir);
      if (!names.includes('404.html')) throw new Error('root 404.html is missing');
    },
  },
});

export default defineConfig({
  site: 'https://exclamationdev.com',
  output: 'static',
  // matches Cloudflare Pages, which 308s /ru to /ru/
  trailingSlash: 'always',
  i18n: {
    defaultLocale: 'az',
    locales: ['az', 'ru', 'en'],
    routing: { prefixDefaultLocale: false },
  },
  build: {
    /**
     * 'auto' left two stylesheets external at ~3.7 kB gzip each. Their
     * download is 0.2 ms; the cost is one render-blocking round trip apiece,
     * measured at ~580 ms each on throttled 4G. Inlining trades ~7 kB of
     * HTML for two fewer blocking requests on the critical path.
     */
    inlineStylesheets: 'always',
  },
  devToolbar: { enabled: false },
  integrations: [localisedErrorPages(), securityHeaders()],
});
